import calendar
import duckdb
import pandas as pd
import plotly.express as px
import streamlit as st

# Set up clean responsive UI layout
st.set_page_config(page_title="Restaurant Sales Analytics", layout="wide")
st.title("📊 Restaurant Customer & Sales Performance Analytics")

# 1. Fetch AWS Secrets automatically from Streamlit's Vault
aws_key = st.secrets["AWS_ACCESS_KEY_ID"]
aws_secret = st.secrets["AWS_SECRET_ACCESS_KEY"]
aws_region = "us-east-1" # st.secrets["AWS_DEFAULT_REGION"]

# 2. Instantiate DuckDB memory engine with secure S3 configurations
@st.cache_resource
def get_duckdb_connection():
    con = duckdb.connect()
    con.execute("INSTALL httpfs; LOAD httpfs;")
    # Pass our credentials into the DuckDB network extension handler
    con.execute(f"SET s3_region='{aws_region}';")
    con.execute(f"SET s3_access_key_id='{aws_key}';")
    con.execute(f"SET s3_secret_access_key='{aws_secret}';")
    
    # Map the entire S3 directory containing your Snappy-Parquet files as a view
    # Using the wildcard ensures all 4 partition files generated by Spark are read as one table
    s3_path = "s3://restaurant-analysis-calvinfr/gold/sales_performance/*.parquet"
    con.execute(f"CREATE OR REPLACE VIEW gold_sales AS SELECT * FROM read_parquet('{s3_path}')")
    return con

con = get_duckdb_connection()

# 3. Sidebar UI Elements for Slicing Dimensions
st.sidebar.title("Filter Analytics")
years_df = con.execute("SELECT DISTINCT YEAR FROM gold_sales ORDER BY YEAR").df()
year_options = years_df["year"].tolist()
selected_year = st.sidebar.selectbox("Select Year:", options = year_options, index = 3)
st.session_state.year = selected_year
st.sidebar.write(f"Selected year is {selected_year}")
months_df = con.execute(f"SELECT DISTINCT MONTH FROM gold_sales WHERE YEAR = {selected_year} ORDER BY MONTH").df()
month_options = months_df["month"].tolist()
selected_month = st.sidebar.selectbox("Select Month:", options = month_options, index = 8)
st.session_state.month = selected_month
st.sidebar.write(f"Selected month is {calendar.month_name[selected_month]}")
item_categories_df = con.execute("SELECT DISTINCT ITEM_CATEGORY FROM gold_sales ORDER BY ITEM_CATEGORY").df()
item_category_options = item_categories_df["ITEM_CATEGORY"].tolist()
selected_item_category = st.sidebar.selectbox("Select Item Category:", options = item_category_options, index = None, placeholder =  "Category")
st.session_state.item_category = selected_item_category
if not selected_item_category:
    st.sidebar.write("Please Select Category")
else:
    st.sidebar.write(f"Selected category is {selected_item_category}")

# 4. Customer Segmentation Dashboard
st.header(f"Customer Segmentation ({calendar.month_name[st.session_state.month]} {st.session_state.year})")
cs_col1, cs_col2, cs_col3 = st.columns(3)

with cs_col1:
    loyalty_segment_query = f"""
        SELECT
            IS_LOYALTY,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY IS_LOYALTY;
    """ # Can change daily, depends on whether customer used loyalty card. Look at how this distribution changes monthly.
    loyalty_segments_df = con.execute(loyalty_segment_query, [st.session_state.year, st.session_state.month]).df()
    loyalty_segments_df["IS_LOYALTY"] = loyalty_segments_df["IS_LOYALTY"].map({True: "Loyal", False: "Non-Loyal"})
    loyalty_segments_chart = px.pie(
        loyalty_segments_df,
        values = "REVENUE",
        names = "IS_LOYALTY",
        title = "Total Sales by Loyalty"
    )
    st.plotly_chart(loyalty_segments_chart)

with cs_col2:
    clv_segment_query = f"""
        SELECT
            CLV_SEGMENT_LABEL AS CLV_SEGMENT,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY CLV_SEGMENT_LABEL;
    """ # Can change monthly.
    clv_segments_df = con.execute(clv_segment_query, [st.session_state.year, st.session_state.month]).df()
    clv_segments_chart = px.pie(
        clv_segments_df,
        values = "REVENUE",
        names = "CLV_SEGMENT",
        title = "Total Sales by CLV Score"
    )
    st.plotly_chart(clv_segments_chart)

with cs_col3:
    vip_segment_query = f"""
        SELECT
            MONTHLY_VIP_STATUS AS VIP_STATUS,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY MONTHLY_VIP_STATUS;
    """ # Can change monthly.
    vip_segments_df = con.execute(vip_segment_query, [st.session_state.year, st.session_state.month]).df()
    vip_segments_df["VIP_STATUS"] = vip_segments_df["VIP_STATUS"].map({True: "VIP", False: "Non-VIP"})
    vip_segments_chart = px.pie(
        vip_segments_df,
        values = "REVENUE",
        names = "VIP_STATUS",
        title = "Total Sales by VIP Status"
    )
    st.plotly_chart(vip_segments_chart)

st.divider()

cs_col4, cs_col5 = st.columns(2)

with cs_col4:
    new_customer_segment_query = f"""
        SELECT
            MONTHLY_NEW_CUSTOMER_STATUS AS NEW_CUSTOMER_STATUS,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY MONTHLY_NEW_CUSTOMER_STATUS;
    """ # Can change monthly.
    new_customer_segments_df = con.execute(new_customer_segment_query, [st.session_state.year, st.session_state.month]).df()
    new_customer_segments_df["NEW_CUSTOMER_STATUS"] = new_customer_segments_df["NEW_CUSTOMER_STATUS"].map({True: "New Customers", False: "Old Customers"})
    new_customer_segments_chart = px.pie(
        new_customer_segments_df,
        values = "REVENUE",
        names = "NEW_CUSTOMER_STATUS",
        title = "Total Sales by Customer Recency"
    )
    st.plotly_chart(new_customer_segments_chart)

with cs_col5:
    churn_risk_segment_query = f"""
        SELECT
            MONTHLY_CHURN_RISK_STATUS AS CHURN_RISK,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY MONTHLY_CHURN_RISK_STATUS;
    """ # Can change monthly.
    churn_risk_segments_df = con.execute(churn_risk_segment_query, [st.session_state.year, st.session_state.month]).df()
    churn_risk_segments_df["CHURN_RISK"] = churn_risk_segments_df["CHURN_RISK"].map({True: "At Risk", False: "Regular"})
    churn_risk_segments_chart = px.pie(
        churn_risk_segments_df,
        values = "REVENUE",
        names = "CHURN_RISK",
        title = "Total Sales by Churn Risk"
    )
    st.plotly_chart(churn_risk_segments_chart)

st.divider()

# 5. Churn Risk Indicator Dashboard
st.header(f"Churn Risk Indicators ({calendar.month_name[st.session_state.month]} {st.session_state.year})")
cri_col1, cri_col2 = st.columns(2)

with cri_col1:
    st.subheader("Average Days Since Last Order")
    avg_days_since_last_order_query = f"""
        SELECT
            MONTHLY_CHURN_RISK_STATUS AS CHURN_RISK,
            AVG(DAYS_SINCE_LAST_ORDER) AS AVG_DSLO
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY MONTHLY_CHURN_RISK_STATUS;
    """
    avg_days_since_last_order_df = con.execute(avg_days_since_last_order_query, [st.session_state.year, st.session_state.month]).df()
    avg_days_since_last_order_df["CHURN_RISK"] = avg_days_since_last_order_df["CHURN_RISK"].map({True: "At Risk", False: "Regular"})
    st.bar_chart(
        data = avg_days_since_last_order_df,
        x = "CHURN_RISK",
        x_label = "Churn Risk",
        y = "AVG_DSLO",
        y_label = "Days Since Last Order",
        color = "CHURN_RISK"
    )

with cri_col2:
    st.subheader("Average Order Gap")
    avg_order_interval_query = f"""
        WITH order_intervals AS (
            SELECT
                DATE_DIFF(
                    'day',
                    LAG(DATE_KEY) OVER(PARTITION BY USER_ID ORDER BY DATE_KEY),
                    DATE_KEY
                ) AS DAYS_BETWEEN_ORDERS,
                MONTHLY_CHURN_RISK_STATUS AS CHURN_RISK,
                year,
                month
            FROM gold_sales
        )

        SELECT
            CHURN_RISK,
            AVG(DAYS_BETWEEN_ORDERS) AS AVG_ORDER_GAP_DAYS
        FROM order_intervals
        WHERE year = ? AND month = ?
        GROUP BY CHURN_RISK;
    """
    avg_order_interval_df = con.execute(avg_order_interval_query, [st.session_state.year, st.session_state.month]).df()
    avg_order_interval_df["CHURN_RISK"] = avg_order_interval_df["CHURN_RISK"].map({True: "At Risk", False: "Regular"})
    st.bar_chart(
        data = avg_order_interval_df,
        x = "CHURN_RISK",
        x_label = "Churn Risk",
        y = "AVG_ORDER_GAP_DAYS",
        y_label = "Average Order Gap (Days)",
        color = "CHURN_RISK"
    )

st.divider()
st.subheader("Total Spend")
total_spend_query = f"""
    SELECT
        MONTHLY_CHURN_RISK_STATUS AS CHURN_RISK,
        SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
        (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
    FROM gold_sales
    WHERE year = ? AND month = ?
    GROUP BY MONTHLY_CHURN_RISK_STATUS;
"""
total_spend_df = con.execute(total_spend_query, [st.session_state.year, st.session_state.month]).df()
total_spend_df["CHURN_RISK"] = total_spend_df["CHURN_RISK"].map({True: "At Risk", False: "Regular"})
st.bar_chart(
    data = total_spend_df,
    x = "CHURN_RISK",
    x_label = "Churn Risk",
    y = "REVENUE",
    y_label = "Total Revenue",
    color = "CHURN_RISK"
)

st.divider()

# 6. Sales Trend and Seasonality Dashboard
st.header(f"Sales Trend and Seasonality ({calendar.month_name[st.session_state.month]} {st.session_state.year})")

yearly_revenue_query = con.execute(
    f"""
        SELECT
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ?;
    """,
    [st.session_state.year]
).df()

yearly_top_product_query = con.execute(
    f"""
        WITH product_revenues AS (
            SELECT
                year,
                ITEM_CATEGORY,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
            FROM gold_sales
            WHERE year = ?
            GROUP BY year, ITEM_CATEGORY
            ORDER BY REVENUE DESC
        )

        SELECT ITEM_CATEGORY FROM product_revenues LIMIT 1;
    """,
    [st.session_state.year]
).df()

monthly_revenue_query = con.execute(
    f"""
        SELECT
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? and month = ?;
    """,
    [st.session_state.year, st.session_state.month] 
).df()

monthly_top_product_query = con.execute(
    f"""
        WITH product_revenues AS (
            SELECT
                year,
                month,
                ITEM_CATEGORY,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
            FROM gold_sales
            WHERE year = ? and month = ?
            GROUP BY year, month, ITEM_CATEGORY
            ORDER BY REVENUE DESC
        )

        SELECT ITEM_CATEGORY FROM product_revenues LIMIT 1;
    """,
    [st.session_state.year, st.session_state.month]
).df()

yearly_revenue = yearly_revenue_query["REVENUE"].item()
monthly_revenue = monthly_revenue_query["REVENUE"].item()
yearly_top_product = yearly_top_product_query["ITEM_CATEGORY"].item()
monthly_top_product = monthly_top_product_query["ITEM_CATEGORY"].item()

sts_kpi1, sts_kpi2 = st.columns(2)
sts_kpi1.metric(f"Total Revenue ({st.session_state.year})", f"${yearly_revenue:,.2f}")
sts_kpi2.metric(f"Total Revenue ({calendar.month_name[st.session_state.month]})", f"${monthly_revenue:,.2f}")

sts_kpi3, sts_kpi4 = st.columns(2)
sts_kpi3.metric(f"Top Product ({st.session_state.year})", f"{yearly_top_product}")
sts_kpi4.metric(f"Top Product ({calendar.month_name[st.session_state.month]})", f"{monthly_top_product}")

yearly_revenue_trend_query = con.execute(
    f"""
        SELECT
            year,
            month,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ?
        GROUP BY year, month
        ORDER BY year, month;
    """,
    [st.session_state.year]
).df()

monthly_revenue_trend_query = con.execute(
    f"""
        SELECT
            year,
            month,
            day,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY year, month, day
        ORDER BY year, month, day;
    """,
    [st.session_state.year, st.session_state.month]
).df()

sts_col1, sts_col2 = st.columns(2)

with sts_col1:
    line_graph_yearly_revenue_trend = px.line(
        yearly_revenue_trend_query,
        x = 'month',
        y = 'REVENUE',
        labels = {"month": "Month", "REVENUE": "Total Monthly Revenue"},
        title = f"Yearly Revenue Trend ({st.session_state.year})"
    )
    st.plotly_chart(line_graph_yearly_revenue_trend)

with sts_col2:
    line_graph_monthly_revenue_trend = px.line(
        monthly_revenue_trend_query,
        x = 'day',
        y = 'REVENUE',
        labels = {"day": "Day", "REVENUE": "Total Daily Revenue"},
        title = f"Monthly Revenue Trend ({calendar.month_name[st.session_state.month]})"
    )
    st.plotly_chart(line_graph_monthly_revenue_trend)

st.divider()

if not selected_item_category:
    st.warning("Please select an item category to review sales trends.")
else:
    yearly_product_revenue_trend_df = con.execute(
        f"""
            SELECT
                year,
                month,
                ITEM_CATEGORY,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
            FROM gold_sales
            WHERE year = ? AND ITEM_CATEGORY = ?
            GROUP BY year, month, ITEM_CATEGORY
            ORDER BY year, month;
        """,
        [st.session_state.year, st.session_state.item_category]
    ).df()

    monthly_product_revenue_trend_df = con.execute(
        f"""
            SELECT
                year,
                month,
                day,
                ITEM_CATEGORY,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS REVENUE
            FROM gold_sales
            WHERE year = ? AND month = ? AND ITEM_CATEGORY = ?
            GROUP BY year, month, day, ITEM_CATEGORY
            ORDER BY year, month, day;
        """,
        [st.session_state.year, st.session_state.month, st.session_state.item_category]
    ).df()

    sts_col3, sts_col4 = st.columns(2)

    with sts_col3:
        line_graph_yearly_product_revenue_trend = px.line(
            yearly_product_revenue_trend_df,
            x = 'month',
            y = 'REVENUE',
            labels = {"month": "Month", "REVENUE": f"Total Monthly Revenue ({st.session_state.item_category})"},
            title = f"{st.session_state.item_category} Yearly Revenue Trend ({st.session_state.year})"
        )
        st.plotly_chart(line_graph_yearly_product_revenue_trend)

    with sts_col4:
        line_graph_monthly_product_revenue_trend = px.line(
            monthly_product_revenue_trend_df,
            x = 'day',
            y = 'REVENUE',
            labels = {"day": "Day", "REVENUE": f"Total Daily Revenue ({st.session_state.item_category})"},
            title = f"{st.session_state.item_category} Monthly Revenue Trend ({calendar.month_name[st.session_state.month]})"
        )
        st.plotly_chart(line_graph_monthly_product_revenue_trend)

st.divider()
st.subheader("Seasonal Revenue")

seasonal_revenue_trend_query = """
    WITH seasonal_revenue AS (
        SELECT
            year,
            month,
            ITEM_PRICE,
            ITEM_QUANTITY,
            OPTION_PRICE,
            OPTION_QUANTITY,
            (
                CASE
                    WHEN month <= 3 THEN 'Winter'
                    WHEN month <= 6 THEN 'Spring'
                    WHEN month <= 9 THEN 'Summer'
                    ELSE 'Fall'
                END
            ) AS SEASON
        FROM gold_sales
    )

    SELECT
        SEASON,
        SUM((ITEM_PRICE * ITEM_QUANTITY) +
        (OPTION_PRICE * OPTION_QUANTITY)) AS SEASONAL_REVENUE
    FROM seasonal_revenue
    WHERE year = ?
    GROUP BY SEASON
"""
seasonal_revenue_trend_df = con.execute(seasonal_revenue_trend_query, [st.session_state.year]).df()
season_order = ['Winter', 'Spring', 'Summer', 'Fall']
seasonal_revenue_trend_df["SEASON"] = pd.Categorical(
    seasonal_revenue_trend_df["SEASON"], 
    categories=season_order, 
    ordered=True
)

st.bar_chart(
    data = seasonal_revenue_trend_df,
    x = "SEASON",
    x_label = "Season",
    y = "SEASONAL_REVENUE",
    y_label = "Seasonal Revenue",
    color = "SEASON"
)

# 7. Loyalty Program Impact
st.header(f"Loyalty Program Impact ({calendar.month_name[st.session_state.month]} {st.session_state.year})")
st.subheader("CLV Scores")
lpi_col1, lpi_col2, lpi_col3 = st.columns(3)

with lpi_col1:
    loyalty_impact_high_clv_query = f"""
        SELECT
            IS_LOYALTY,
            COUNT(CLV_SEGMENT_LABEL) AS CLV_SEGMENT_COUNT
        FROM gold_sales
        WHERE year = ? AND month = ? AND CLV_SEGMENT_LABEL = ?
        GROUP BY IS_LOYALTY;
    """
    loyalty_impact_high_clv_df = con.execute(loyalty_impact_high_clv_query, [st.session_state.year, st.session_state.month, "High Value"]).df()
    loyalty_impact_high_clv_df["IS_LOYALTY"] = loyalty_impact_high_clv_df["IS_LOYALTY"].map({True: "Loyal", False: "Non-Loyal"})
    loyalty_impact_high_clv_chart = px.pie(
        loyalty_impact_high_clv_df,
        values = "CLV_SEGMENT_COUNT",
        names = "IS_LOYALTY",
        title = "Total Orders by High Value"
    )
    st.plotly_chart(loyalty_impact_high_clv_chart)

with lpi_col2:
    loyalty_impact_medium_clv_query = f"""
        SELECT
            IS_LOYALTY,
            COUNT(CLV_SEGMENT_LABEL) AS CLV_SEGMENT_COUNT
        FROM gold_sales
        WHERE year = ? AND month = ? AND CLV_SEGMENT_LABEL = ?
        GROUP BY IS_LOYALTY;
    """
    loyalty_impact_medium_clv_df = con.execute(loyalty_impact_medium_clv_query, [st.session_state.year, st.session_state.month, "Medium Value"]).df()
    loyalty_impact_medium_clv_df["IS_LOYALTY"] = loyalty_impact_medium_clv_df["IS_LOYALTY"].map({True: "Loyal", False: "Non-Loyal"})
    loyalty_impact_medium_clv_chart = px.pie(
        loyalty_impact_medium_clv_df,
        values = "CLV_SEGMENT_COUNT",
        names = "IS_LOYALTY",
        title = "Total Orders by Medium Value"
    )
    st.plotly_chart(loyalty_impact_medium_clv_chart)

with lpi_col3:
    loyalty_impact_low_clv_query = f"""
        SELECT
            IS_LOYALTY,
            COUNT(CLV_SEGMENT_LABEL) AS CLV_SEGMENT_COUNT
        FROM gold_sales
        WHERE year = ? AND month = ? AND CLV_SEGMENT_LABEL = ?
        GROUP BY IS_LOYALTY;
    """
    loyalty_impact_low_clv_df = con.execute(loyalty_impact_low_clv_query, [st.session_state.year, st.session_state.month, "Low Value"]).df()
    loyalty_impact_low_clv_df["IS_LOYALTY"] = loyalty_impact_low_clv_df["IS_LOYALTY"].map({True: "Loyal", False: "Non-Loyal"})
    loyalty_impact_low_clv_chart = px.pie(
        loyalty_impact_low_clv_df,
        values = "CLV_SEGMENT_COUNT",
        names = "IS_LOYALTY",
        title = "Total Orders by Low Value"
    )
    st.plotly_chart(loyalty_impact_low_clv_chart)

st.divider()
st.subheader("Average Order Value")
loyalty_impact_avg_spend_query = f"""
    WITH order_revenues AS (
        SELECT
            ORDER_ID,
            IS_LOYALTY,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS ORDER_REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY ORDER_ID, IS_LOYALTY
    )

    SELECT
        IS_LOYALTY,
        AVG(ORDER_REVENUE) AS AVG_ORDER_VALUE
    FROM order_revenues
    GROUP BY IS_LOYALTY;
"""
loyalty_impact_avg_spend_df = con.execute(loyalty_impact_avg_spend_query, [st.session_state.year, st.session_state.month]).df()
loyalty_impact_avg_spend_df["IS_LOYALTY"] = loyalty_impact_avg_spend_df["IS_LOYALTY"].map({True: "Loyal", False: "Non-Loyal"})
st.bar_chart(
    data = loyalty_impact_avg_spend_df,
    x = "IS_LOYALTY",
    x_label = "Loyalty Status",
    y = "AVG_ORDER_VALUE",
    y_label = "Average Order Value",
    color = "IS_LOYALTY"
)

st.subheader("Average Order Gap")
loyalty_impact_avg_order_interval_query = f"""
    WITH order_intervals AS (
        SELECT
            DATE_DIFF(
                'day',
                LAG(DATE_KEY) OVER(PARTITION BY USER_ID ORDER BY DATE_KEY),
                DATE_KEY
            ) AS DAYS_BETWEEN_ORDERS,
            IS_LOYALTY,
            MONTHLY_CHURN_RISK_STATUS AS CHURN_RISK,
            year,
            month
        FROM gold_sales
    )

    SELECT
        IS_LOYALTY,
        AVG(DAYS_BETWEEN_ORDERS) AS AVG_ORDER_GAP_DAYS
    FROM order_intervals
    WHERE year = ? AND month = ?
    GROUP BY IS_LOYALTY;
"""
loyalty_impact_avg_order_interval_df = con.execute(loyalty_impact_avg_order_interval_query, [st.session_state.year, st.session_state.month]).df()
loyalty_impact_avg_order_interval_df["IS_LOYALTY"] = loyalty_impact_avg_order_interval_df["IS_LOYALTY"].map({True: "Loyal", False: "Non-Loyal"})
st.bar_chart(
    data = loyalty_impact_avg_order_interval_df,
    x = "IS_LOYALTY",
    x_label = "Loyalty Status",
    y = "AVG_ORDER_GAP_DAYS",
    y_label = "Average Order Gap (Days)",
    color = "IS_LOYALTY"
)

# 8. Location Performance Dashboard
st.header(f"Location Performance ({calendar.month_name[st.session_state.month]} {st.session_state.year})")
st.subheader("Total Revenue")
lp_col1, lp_col2 = st.columns(2)

with lp_col1:
    top_location_impact_total_spend_query = f"""
        SELECT
            RESTAURANT_ID,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS TOTAL_REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY RESTAURANT_ID
        ORDER BY TOTAL_REVENUE DESC
        LIMIT 10;
    """
    top_location_impact_total_spend_df = con.execute(top_location_impact_total_spend_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_top_restaurants_order_revenue = px.bar(
        top_location_impact_total_spend_df,
        x = 'TOTAL_REVENUE',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'TOTAL_REVENUE': 'Total Order Revenue', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Top 10 Restaurants by Order Revenue'
    )
    st.plotly_chart(bar_chart_top_restaurants_order_revenue)

with lp_col2:
    bottom_location_impact_total_spend_query = f"""
        SELECT
            RESTAURANT_ID,
            SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
            (OPTION_PRICE * OPTION_QUANTITY))) AS TOTAL_REVENUE
        FROM gold_sales
        WHERE year = ? AND month = ?
        GROUP BY RESTAURANT_ID
        ORDER BY TOTAL_REVENUE
        LIMIT 10;
    """
    bottom_location_impact_total_spend_df = con.execute(bottom_location_impact_total_spend_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_bottom_restaurants_order_revenue = px.bar(
        bottom_location_impact_total_spend_df,
        x = 'TOTAL_REVENUE',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'TOTAL_REVENUE': 'Total Order Revenue', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Bottom 10 Restaurants by Order Revenue'
    )
    st.plotly_chart(bar_chart_bottom_restaurants_order_revenue)

st.divider()
st.subheader("Average Order Value")
lp_col3, lp_col4 = st.columns(2)

with lp_col3:
    top_location_impact_avg_spend_query = f"""
        WITH order_revenues AS (
            SELECT
                ORDER_ID,
                RESTAURANT_ID,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS ORDER_REVENUE
            FROM gold_sales
            WHERE year = ? AND month = ?
            GROUP BY ORDER_ID, RESTAURANT_ID
        )

        SELECT
            RESTAURANT_ID,
            AVG(ORDER_REVENUE) AS AVG_ORDER_VALUE
        FROM order_revenues
        GROUP BY RESTAURANT_ID
        ORDER BY AVG_ORDER_VALUE DESC
        LIMIT 10;
    """
    top_location_impact_avg_spend_df = con.execute(top_location_impact_avg_spend_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_top_restaurants_avg_spend = px.bar(
        top_location_impact_avg_spend_df,
        x = 'AVG_ORDER_VALUE',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'AVG_ORDER_VALUE': 'Average Order Value', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Top 10 Restaurants by Average Order Value'
    )
    st.plotly_chart(bar_chart_top_restaurants_avg_spend)

with lp_col4:
    bottom_location_impact_avg_spend_query = f"""
        WITH order_revenues AS (
            SELECT
                ORDER_ID,
                RESTAURANT_ID,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS ORDER_REVENUE
            FROM gold_sales
            WHERE year = ? AND month = ?
            GROUP BY ORDER_ID, RESTAURANT_ID
        )

        SELECT
            RESTAURANT_ID,
            AVG(ORDER_REVENUE) AS AVG_ORDER_VALUE
        FROM order_revenues
        GROUP BY RESTAURANT_ID
        ORDER BY AVG_ORDER_VALUE
        LIMIT 10;
    """
    bottom_location_impact_avg_spend_df = con.execute(bottom_location_impact_avg_spend_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_bottom_restaurants_avg_spend = px.bar(
        bottom_location_impact_avg_spend_df,
        x = 'AVG_ORDER_VALUE',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'AVG_ORDER_VALUE': 'Average Order Value', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Bottom 10 Restaurants by Average Order Value'
    )
    st.plotly_chart(bar_chart_bottom_restaurants_avg_spend)

st.divider()
st.subheader("Average Order Gap")
lp_col5, lp_col6 = st.columns(2)

with lp_col5:
    top_location_impact_avg_order_interval_query = f"""
        WITH order_intervals AS (
            SELECT
                DATE_DIFF(
                    'day',
                    LAG(DATE_KEY) OVER(PARTITION BY USER_ID ORDER BY DATE_KEY),
                    DATE_KEY
                ) AS DAYS_BETWEEN_ORDERS,
                RESTAURANT_ID,
                year,
                month
            FROM gold_sales
        )

        SELECT
            RESTAURANT_ID,
            AVG(DAYS_BETWEEN_ORDERS) AS AVG_ORDER_GAP_DAYS
        FROM order_intervals
        WHERE year = ? AND month = ?
        GROUP BY RESTAURANT_ID
        ORDER BY AVG_ORDER_GAP_DAYS DESC
        LIMIT 10;
    """
    top_location_impact_avg_order_interval_df = con.execute(top_location_impact_avg_order_interval_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_top_restaurants_avg_order_interval = px.bar(
        top_location_impact_avg_order_interval_df,
        x = 'AVG_ORDER_GAP_DAYS',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'AVG_ORDER_GAP_DAYS': 'Average Order Gap (Days)', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Top 10 Restaurants by Average Order Gap (Days)'
    )
    st.plotly_chart(bar_chart_top_restaurants_avg_order_interval)

with lp_col6:
    bottom_location_impact_avg_order_interval_query = f"""
        WITH order_intervals AS (
            SELECT
                DATE_DIFF(
                    'day',
                    LAG(DATE_KEY) OVER(PARTITION BY USER_ID ORDER BY DATE_KEY),
                    DATE_KEY
                ) AS DAYS_BETWEEN_ORDERS,
                RESTAURANT_ID,
                year,
                month
            FROM gold_sales
        )

        SELECT
            RESTAURANT_ID,
            AVG(DAYS_BETWEEN_ORDERS) AS AVG_ORDER_GAP_DAYS
        FROM order_intervals
        WHERE year = ? AND month = ?
        GROUP BY RESTAURANT_ID
        ORDER BY AVG_ORDER_GAP_DAYS
        LIMIT 10;
    """
    bottom_location_impact_avg_order_interval_df = con.execute(bottom_location_impact_avg_order_interval_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_bottom_restaurants_avg_order_interval = px.bar(
        bottom_location_impact_avg_order_interval_df,
        x = 'AVG_ORDER_GAP_DAYS',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'AVG_ORDER_GAP_DAYS': 'Average Order Gap (Days)', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Bottom 10 Restaurants by Average Order Value'
    )
    st.plotly_chart(bar_chart_bottom_restaurants_avg_order_interval)

st.divider()
st.subheader("Maximum Daily Revenue")
lp_col7, lp_col8 = st.columns(2)

with lp_col7:
    top_location_impact_max_daily_spend_query = f"""
        WITH order_revenues AS (
            SELECT
                RESTAURANT_ID,
                day,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS DAILY_ORDER_REVENUE
            FROM gold_sales
            WHERE year = ? AND month = ?
            GROUP BY RESTAURANT_ID, day
        )

        SELECT
            RESTAURANT_ID,
            MAX(DAILY_ORDER_REVENUE) AS MAX_DAILY_REVENUE
        FROM order_revenues
        GROUP BY RESTAURANT_ID
        ORDER BY MAX_DAILY_REVENUE DESC
        LIMIT 10;
    """
    top_location_impact_max_daily_spend_df = con.execute(top_location_impact_max_daily_spend_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_top_restaurants_max_daily_spend = px.bar(
        top_location_impact_max_daily_spend_df,
        x = 'MAX_DAILY_REVENUE',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'MAX_DAILY_REVENUE': 'Maximum Daily Revenue', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Top 10 Restaurants by Maximum Daily Revenue'
    )
    st.plotly_chart(bar_chart_top_restaurants_max_daily_spend)

with lp_col8:
    bottom_location_impact_max_daily_spend_query = f"""
        WITH order_revenues AS (
            SELECT
                RESTAURANT_ID,
                day,
                SUM(((ITEM_PRICE * ITEM_QUANTITY) + 
                (OPTION_PRICE * OPTION_QUANTITY))) AS DAILY_ORDER_REVENUE
            FROM gold_sales
            WHERE year = ? AND month = ?
            GROUP BY RESTAURANT_ID, day
        )

        SELECT
            RESTAURANT_ID,
            MAX(DAILY_ORDER_REVENUE) AS MAX_DAILY_REVENUE
        FROM order_revenues
        GROUP BY RESTAURANT_ID
        ORDER BY MAX_DAILY_REVENUE
        LIMIT 10;
    """
    bottom_location_impact_max_daily_spend_df = con.execute(bottom_location_impact_max_daily_spend_query, [st.session_state.year, st.session_state.month]).df()
    bar_chart_bottom_restaurants_max_daily_spend = px.bar(
        bottom_location_impact_max_daily_spend_df,
        x = 'MAX_DAILY_REVENUE',
        y = 'RESTAURANT_ID',
        barmode = 'group',
        orientation = 'h',
        labels = {'MAX_DAILY_REVENUE': 'Maximum Daily Revenue', 'RESTAURANT_ID': 'Restaurant ID'},
        title = 'Bottom 10 Restaurants by Maximum Daily Revenue'
    )
    st.plotly_chart(bar_chart_bottom_restaurants_max_daily_spend)

st.divider()

st.header(f"Pricing Effectiveness ({calendar.month_name[st.session_state.month]} {st.session_state.year})")
st.subheader("How revenue varies amongst 10 equally-sized price buckets")
pe_kpi_1, pe_kpi_2 = st.columns(2)

max_item_price = con.execute(
    """
    SELECT
        MAX(CAST(ITEM_PRICE AS DOUBLE)) AS PRICE
    FROM gold_sales
    WHERE year = ? AND month = ?;
    """,
    [st.session_state.year, st.session_state.month]
).df()["PRICE"].item()

min_item_price = con.execute(
    """
    SELECT
        MIN(CAST(ITEM_PRICE AS DOUBLE)) AS PRICE
    FROM gold_sales;
    """
).df()["PRICE"].item()

pe_kpi_1.metric(f"Minimum Item Price: ", f"${min_item_price}")
pe_kpi_2.metric(f"Maximum Item Price: ", f"${max_item_price}")

st.divider()

price_effectiveness_query = f"""
    WITH item_price_buckets AS (
        SELECT
            year,
            month,
            ITEM_PRICE,
            ITEM_QUANTITY,
            OPTION_PRICE,
            OPTION_QUANTITY,
            NTILE(10) OVER(PARTITION BY year, month ORDER BY ITEM_PRICE) AS PRICE_BUCKET
        FROM gold_sales
    )

    SELECT
        PRICE_BUCKET,
        SUM((ITEM_PRICE * ITEM_QUANTITY) +
        (OPTION_PRICE * OPTION_QUANTITY)) AS BUCKET_REVENUE
    FROM item_price_buckets
    WHERE year = ? AND month = ?
    GROUP BY PRICE_BUCKET
    ORDER BY BUCKET_REVENUE;
"""
price_effectiveness_df = con.execute(price_effectiveness_query, [st.session_state.year, st.session_state.month]).df()

st.bar_chart(
    data = price_effectiveness_df,
    x = "PRICE_BUCKET",
    x_label = "Bucket Number (Lowest to Highest Price)",
    y = "BUCKET_REVENUE",
    y_label = "Bucket Revenue",
    color = "PRICE_BUCKET"
)
